on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

name: Standard

jobs:
  ci_test:
    name: CI - Test
    if: ${{ success() && github.event_name != 'pull_request_target' && github.event_name != 'push'}}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Event Name
        id: github_event_name
        run: echo '${{ github.event_name }}'
      - uses: actions/checkout@v3
        if: ${{ github.event_name == 'pull_request' }}
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/checkout@v3
        if: ${{ github.event_name != 'pull_request' }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - run: yarn install
      - run: npx prisma generate
      - run: yarn run test:ci
  ci_docker_dev:
    name: CI Docker - Dev
    needs: ci_test
    if: ${{ success() && github.event_name != 'pull_request_target' && github.event_name != 'push'}}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Event Name
        id: github_event_name
        run: echo '${{ github.event_name }}'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: qzzdocker24/api-denjihost:${{ github.sha}}, qzzdocker24/api-denjihost:latest
  deploy:
    name: Deploy to K8S
    needs: ci_docker_dev
    if: ${{ success() && github.event_name != 'pull_request_target' && github.event_name != 'push'}}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Event Name
        id: github_event_name
        run: echo '${{ github.event_name }}'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: GabSnow24/k8s-denjihost
          token: ${{ secrets.GH_PAT }}
      - name: Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1
      - name: Update K8S
        run: |
          cd kube
          cd dev
          kustomize edit set image api-denjihost=qzzdocker24/api-denjihost:${{github.sha}}
      - name: Commit tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "chore: change image tag"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          force_with_lease: true
